[2013-11-01 13:16:27] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /bundles/framework/images/input_bg.gif"" at C:\xampp\htdocs\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 116 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /bundles/framework/images/input_bg.gif\" at C:\\xampp\\htdocs\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:116, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-01 13:16:44] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /bundles/framework/images/input_bg.gif"" at C:\xampp\htdocs\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 116 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /bundles/framework/images/input_bg.gif\" at C:\\xampp\\htdocs\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:116, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-01 17:16:09] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /devdurable/"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /devdurable/\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-01 17:17:44] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /devdurable/"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /devdurable/\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-01 17:18:29] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /devdurable"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /devdurable\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-01 17:18:48] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /devdurable/article=1"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /devdurable/article=1\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-01 17:19:07] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /devdurable/article=1"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /devdurable/article=1\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-01 17:19:28] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /devdurable/article=1"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /devdurable/article=1\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-01 17:19:37] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /devdurable/article=1"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /devdurable/article=1\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-01 17:44:23] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /devdurable/article=1"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /devdurable/article=1\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-11 01:42:12] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/fondTR.png"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/fondTR.png\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-11 01:42:46] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/fondTR.png"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/fondTR.png\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-11 01:45:47] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/fondTR.png"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/fondTR.png\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-11 01:47:01] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/fondTR.png"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/fondTR.png\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-11 01:48:49] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/fondTR.png"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/fondTR.png\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-11 01:49:32] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/fondTR.png"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/fondTR.png\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-11 01:50:48] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/fondTR.png"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/fondTR.png\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-11 01:50:51] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/fondTR.png"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/fondTR.png\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-11 01:53:35] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/fondTR.png"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/fondTR.png\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-11 12:23:27] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /devdurable/sc=2"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /devdurable/sc=2\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-11 12:24:17] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /devdurable/sc=2"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /devdurable/sc=2\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-11 12:40:34] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /devdurable/sc=1"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /devdurable/sc=1\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:30)"} []
[2013-11-12 20:10:24] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /devdurable/so=10"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /devdurable/so=10\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:49)"} []
[2013-11-17 11:28:47] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /images/close-icone.png"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /images/close-icone.png\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:49)"} []
[2013-11-17 13:25:42] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1883 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1883, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:49)"} []
[2013-11-17 18:09:18] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:09:18] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:10:34] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:10:34] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:11:44] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:11:45] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:12:13] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:12:13] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:13:21] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:13:21] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:13:39] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:13:39] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:14:37] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:14:37] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:14:49] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:14:49] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:14:51] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:14:52] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:15:38] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:15:38] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:16:06] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:16:06] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:16:08] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:16:08] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:16:19] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:16:19] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:17:26] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:17:26] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:17:30] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:17:30] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:17:53] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:17:53] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:18:30] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:18:30] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:18:42] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:18:43] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:19:08] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:19:08] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:19:32] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:19:32] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:19:44] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:19:44] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:21:05] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:21:06] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:21:54] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:21:54] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:22:40] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:22:40] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:23:05] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:23:05] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:23:41] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:23:41] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:24:13] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:24:13] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:24:24] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /css/sky.jpg"" at C:\xampp\htdocs\DeveloppementDurable\app\cache\prod\classes.php line 1881 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2013-11-17 18:24:25] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /css/sky.jpg\" at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1881, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\xampp\\htdocs\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:270)"} []
[2014-01-18 09:23:42] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /145"" at C:\wamp\www\DeveloppementDurable\app\cache\prod\classes.php line 1893 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /145\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 09:23:43] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /145\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 09:25:04] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /d"" at C:\wamp\www\DeveloppementDurable\app\cache\prod\classes.php line 1893 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /d\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 09:25:04] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /d\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 09:41:53] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /hh"" at C:\wamp\www\DeveloppementDurable\app\cache\prod\classes.php line 1893 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /hh\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 09:41:53] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /hh\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 09:42:26] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /s"" at C:\wamp\www\DeveloppementDurable\app\cache\prod\classes.php line 1893 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /s\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 09:42:26] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /s\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 09:51:28] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /sc"" at C:\wamp\www\DeveloppementDurable\app\cache\prod\classes.php line 1893 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /sc\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 09:51:28] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /sc\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 09:53:45] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /sc"" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 116 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /sc\" at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:116, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 09:53:46] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /sc\" at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:116, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 09:57:15] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /ddd"" at C:\wamp\www\DeveloppementDurable\app\cache\prod\classes.php line 1893 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /ddd\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 09:57:15] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /ddd\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 10:19:44] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /s"" at C:\wamp\www\DeveloppementDurable\app\cache\prod\classes.php line 1893 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /s\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 10:19:44] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /s\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 10:20:42] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /s"" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 116 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /s\" at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:116, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 10:20:42] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /s\" at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:116, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 11:31:09] request.INFO: Matched route "article_dev_show" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showAction", "id": "24", "_route": "article_dev_show") [] []
[2014-01-18 11:31:09] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-18 11:31:09] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-18 11:31:09] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-18 11:31:09] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-18 11:31:32] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /sc=h"" at C:\wamp\www\DeveloppementDurable\app\cache\prod\classes.php line 1893 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /sc=h\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 11:31:32] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /sc=h\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 11:34:30] request.INFO: Matched route "article_dev_show" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showAction", "id": "24", "_route": "article_dev_show") [] []
[2014-01-18 11:34:30] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-18 11:34:30] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-18 11:34:30] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-18 11:34:30] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-18 11:35:17] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /sc=h"" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Component\HttpKernel\EventListener\RouterListener.php line 116 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /sc=h\" at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:116, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 11:35:18] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /sc=h\" at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Component\\HttpKernel\\EventListener\\RouterListener.php:116, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 11:38:27] request.INFO: Matched route "article_dev_show" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showAction", "id": "2", "_route": "article_dev_show") [] []
[2014-01-18 11:38:27] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-18 11:38:27] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-18 11:38:27] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-18 11:38:27] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-18 11:38:32] request.INFO: Matched route "article_dev_show" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showAction", "id": "2", "_route": "article_dev_show") [] []
[2014-01-18 11:38:32] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-18 11:38:32] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-18 11:38:32] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-18 11:38:32] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-18 11:38:34] request.INFO: Matched route "article_dev_show" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showAction", "id": "2", "_route": "article_dev_show") [] []
[2014-01-18 11:38:34] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-18 11:38:34] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-18 11:38:34] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-18 11:38:34] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-18 11:38:40] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /sc=h"" at C:\wamp\www\DeveloppementDurable\app\cache\prod\classes.php line 1893 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /sc=h\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 11:38:40] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /sc=h\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 11:38:46] request.INFO: Matched route "article_dev_show" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showAction", "id": "4", "_route": "article_dev_show") [] []
[2014-01-18 11:38:46] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-18 11:38:46] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-18 11:38:46] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-18 11:38:46] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-18 11:38:51] request.INFO: Matched route "article_dev_show" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showAction", "id": "1", "_route": "article_dev_show") [] []
[2014-01-18 11:38:51] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-18 11:38:51] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-18 11:38:51] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-18 11:38:51] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-18 11:39:13] request.INFO: Matched route "article_dev_show" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showAction", "id": "1", "_route": "article_dev_show") [] []
[2014-01-18 11:39:13] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-18 11:39:13] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-18 11:39:13] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-18 11:39:13] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-18 11:39:46] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /sc=f"" at C:\wamp\www\DeveloppementDurable\app\cache\prod\classes.php line 1893 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /sc=f\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 11:39:47] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /sc=f\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 11:40:01] request.INFO: Matched route "article_dev_show" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showAction", "id": "600", "_route": "article_dev_show") [] []
[2014-01-18 11:40:01] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-18 11:40:02] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-18 11:40:02] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-18 11:40:02] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-18 11:40:07] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /sc=r"" at C:\wamp\www\DeveloppementDurable\app\cache\prod\classes.php line 1893 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /sc=r\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 11:40:07] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /sc=r\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 11:41:19] request.INFO: Matched route "article_dev_show" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showAction", "id": "600", "_route": "article_dev_show") [] []
[2014-01-18 11:41:19] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-18 11:41:19] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-18 11:41:19] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-18 11:41:19] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-18 11:41:22] request.INFO: Matched route "article_dev_show" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showAction", "id": "6", "_route": "article_dev_show") [] []
[2014-01-18 11:41:22] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-18 11:41:22] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-18 11:41:22] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-18 11:41:22] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-18 11:41:25] request.INFO: Matched route "article_dev_show" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showAction", "id": "1", "_route": "article_dev_show") [] []
[2014-01-18 11:41:25] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-18 11:41:25] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-18 11:41:25] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-18 11:41:25] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-18 11:43:31] request.INFO: Matched route "article_dev_show" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showAction", "id": "111", "_route": "article_dev_show") [] []
[2014-01-18 11:43:31] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-18 11:43:31] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-18 11:43:31] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-18 11:43:31] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-18 11:44:10] request.INFO: Matched route "article_dev_show" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showAction", "id": "111", "_route": "article_dev_show") [] []
[2014-01-18 11:44:10] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-18 11:44:10] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-18 11:44:10] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-18 11:44:10] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-18 11:44:14] request.INFO: Matched route "article_dev_show" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showAction", "id": "111", "_route": "article_dev_show") [] []
[2014-01-18 11:44:14] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-18 11:44:14] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-18 11:44:14] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-18 11:44:14] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-18 11:44:33] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /sc=g"" at C:\wamp\www\DeveloppementDurable\app\cache\prod\classes.php line 1893 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /sc=g\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 11:44:33] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /sc=g\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 11:48:00] request.INFO: Matched route "article_dev_show" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showAction", "id": "10", "_route": "article_dev_show") [] []
[2014-01-18 11:48:00] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-18 11:48:00] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-18 11:48:00] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-18 11:48:00] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-18 11:48:12] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /f"" at C:\wamp\www\DeveloppementDurable\app\cache\prod\classes.php line 1893 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /f\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 11:48:12] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /f\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 11:49:51] request.INFO: Matched route "article_dev_show" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showAction", "id": "211", "_route": "article_dev_show") [] []
[2014-01-18 11:49:51] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-18 11:49:51] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-18 11:49:51] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-18 11:49:51] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-18 11:50:11] request.INFO: Matched route "article_dev_show" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showAction", "id": "211", "_route": "article_dev_show") [] []
[2014-01-18 11:50:11] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-18 11:50:11] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-18 11:50:11] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-18 11:50:11] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-18 11:55:16] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /sc=ff"" at C:\wamp\www\DeveloppementDurable\app\cache\prod\classes.php line 1893 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /sc=ff\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 11:55:16] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /sc=ff\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 11:56:33] request.INFO: Matched route "article_dev_show" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showAction", "id": "211", "_route": "article_dev_show") [] []
[2014-01-18 11:56:33] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-18 11:56:33] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-18 11:56:33] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-18 11:56:33] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-18 12:00:16] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /sc=dd"" at C:\wamp\www\DeveloppementDurable\app\cache\prod\classes.php line 1893 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /sc=dd\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 12:00:16] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /sc=dd\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 12:00:28] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "No route found for "GET /g"" at C:\wamp\www\DeveloppementDurable\app\cache\prod\classes.php line 1893 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /g\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-18 12:00:28] request.ERROR: Exception thrown when handling an exception (Twig_Error_Runtime: An exception has been thrown during the rendering of a template ("The security context contains no authentication token. One possible reason may be that there is no firewall configured for this URL.") in "::base.html.twig" at line 49.) {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: No route found for \"GET /g\" at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\classes.php:1893, Symfony\\Component\\Routing\\Exception\\ResourceNotFoundException:  at C:\\wamp\\www\\DeveloppementDurable\\app\\cache\\prod\\appProdUrlMatcher.php:356)"} []
[2014-01-19 22:16:11] request.INFO: Matched route "article_dev_article" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showTheArticleAction", "idSc": "20", "idAr": "39", "_route": "article_dev_article") [] []
[2014-01-19 22:16:11] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-19 22:16:11] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-19 22:16:11] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-19 22:16:11] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-19 22:16:30] request.INFO: Matched route "article_dev_article" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showTheArticleAction", "idSc": "20", "idAr": "39", "_route": "article_dev_article") [] []
[2014-01-19 22:16:30] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-19 22:16:30] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-19 22:16:30] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-19 22:16:30] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-19 22:17:09] request.INFO: Matched route "article_dev_article" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showTheArticleAction", "idSc": "3", "idAr": "12", "_route": "article_dev_article") [] []
[2014-01-19 22:17:09] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-19 22:17:10] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-19 22:17:10] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-19 22:17:10] security.DEBUG: Write SecurityContext in the session [] []
[2014-01-19 22:17:22] request.INFO: Matched route "article_dev_article" (parameters: "_controller": "UTBM\ArticleDevBundle\Controller\ArticleDevController::showTheArticleAction", "idSc": "18", "idAr": "30", "_route": "article_dev_article") [] []
[2014-01-19 22:17:22] security.INFO: Populated SecurityContext with an anonymous Token [] []
[2014-01-19 22:17:22] request.ERROR: Uncaught PHP Exception Symfony\Component\HttpKernel\Exception\NotFoundHttpException: "La page demandée est introuvable !" at C:\wamp\www\DeveloppementDurable\vendor\symfony\symfony\src\Symfony\Bundle\FrameworkBundle\Controller\Controller.php line 149 {"exception":"[object] (Symfony\\Component\\HttpKernel\\Exception\\NotFoundHttpException: La page demand\u00e9e est introuvable ! at C:\\wamp\\www\\DeveloppementDurable\\vendor\\symfony\\symfony\\src\\Symfony\\Bundle\\FrameworkBundle\\Controller\\Controller.php:149)"} []
[2014-01-19 22:17:22] security.INFO: No expression found; abstaining from voting. [] []
[2014-01-19 22:17:22] security.DEBUG: Write SecurityContext in the session [] []
